---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tester
  labels:
    app: app-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tester
  template:
    metadata:
      labels:
        app: app-tester
    spec:
      containers:
        - name: app-tester-container
          image: southamerica-east1-docker.pkg.dev/plataformagovdigital-gcp-main/mti-dev-td/app-tester:latest
          envFrom:
            - configMapRef:
                name: app-tester-cfg
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 600
            periodSeconds: 100
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: test-results
              mountPath: /tests/results
      volumes:
        - name: test-results
          emptyDir: {}
